/**
 * Default Keyboard Shortcuts — F052: Keyboard Shortcuts System
 *
 * Defines default shortcut bindings for common diagram operations.
 * These can be customized by users and persisted to localStorage.
 */

import type { ShortcutBinding } from './types';

export const DEFAULT_SHORTCUTS: ShortcutBinding[] = [
  // ─── Editing ─────────────────────────────────────────────────────
  {
    id: 'edit.undo',
    keys: ['z'],
    modifiers: ['ctrl'],
    description: 'Undo last action',
    scope: 'global',
    category: 'editing',
  },
  {
    id: 'edit.redo',
    keys: ['z'],
    modifiers: ['ctrl', 'shift'],
    description: 'Redo last undone action',
    scope: 'global',
    category: 'editing',
  },
  {
    id: 'edit.delete',
    keys: ['delete'],
    description: 'Delete selected item',
    scope: 'canvas',
    category: 'editing',
  },
  {
    id: 'edit.backspace',
    keys: ['backspace'],
    description: 'Delete selected item',
    scope: 'canvas',
    category: 'editing',
  },
  {
    id: 'edit.copy',
    keys: ['c'],
    modifiers: ['ctrl'],
    description: 'Copy selected item',
    scope: 'canvas',
    category: 'editing',
  },
  {
    id: 'edit.cut',
    keys: ['x'],
    modifiers: ['ctrl'],
    description: 'Cut selected item',
    scope: 'canvas',
    category: 'editing',
  },
  {
    id: 'edit.paste',
    keys: ['v'],
    modifiers: ['ctrl'],
    description: 'Paste copied item',
    scope: 'canvas',
    category: 'editing',
  },
  {
    id: 'edit.duplicate',
    keys: ['d'],
    modifiers: ['ctrl'],
    description: 'Duplicate selected item',
    scope: 'canvas',
    category: 'editing',
  },
  {
    id: 'edit.selectAll',
    keys: ['a'],
    modifiers: ['ctrl'],
    description: 'Select all items',
    scope: 'canvas',
    category: 'editing',
  },
  {
    id: 'edit.deselectAll',
    keys: ['escape'],
    description: 'Deselect all items',
    scope: 'canvas',
    category: 'editing',
  },

  // ─── Canvas ──────────────────────────────────────────────────────
  {
    id: 'canvas.clear',
    keys: ['k'],
    modifiers: ['ctrl', 'shift'],
    description: 'Clear canvas',
    scope: 'canvas',
    category: 'canvas',
  },
  {
    id: 'canvas.resize',
    keys: ['r'],
    modifiers: ['ctrl'],
    description: 'Resize canvas',
    scope: 'canvas',
    category: 'canvas',
  },
  {
    id: 'canvas.export',
    keys: ['e'],
    modifiers: ['ctrl'],
    description: 'Export diagram',
    scope: 'canvas',
    category: 'canvas',
  },
  {
    id: 'canvas.toggleGrid',
    keys: ['g'],
    modifiers: ['ctrl'],
    description: 'Toggle grid visibility',
    scope: 'canvas',
    category: 'canvas',
  },

  // ─── Navigation ──────────────────────────────────────────────────
  {
    id: 'nav.zoomIn',
    keys: ['+'],
    modifiers: ['ctrl'],
    description: 'Zoom in',
    scope: 'canvas',
    category: 'navigation',
  },
  {
    id: 'nav.zoomOut',
    keys: ['-'],
    modifiers: ['ctrl'],
    description: 'Zoom out',
    scope: 'canvas',
    category: 'navigation',
  },
  {
    id: 'nav.zoomReset',
    keys: ['0'],
    modifiers: ['ctrl'],
    description: 'Reset zoom',
    scope: 'canvas',
    category: 'navigation',
  },
  {
    id: 'nav.fitToScreen',
    keys: ['f'],
    modifiers: ['ctrl'],
    description: 'Fit canvas to screen',
    scope: 'canvas',
    category: 'navigation',
  },
  {
    id: 'nav.panUp',
    keys: ['arrowup'],
    modifiers: ['shift'],
    description: 'Pan canvas up',
    scope: 'canvas',
    category: 'navigation',
  },
  {
    id: 'nav.panDown',
    keys: ['arrowdown'],
    modifiers: ['shift'],
    description: 'Pan canvas down',
    scope: 'canvas',
    category: 'navigation',
  },
  {
    id: 'nav.panLeft',
    keys: ['arrowleft'],
    modifiers: ['shift'],
    description: 'Pan canvas left',
    scope: 'canvas',
    category: 'navigation',
  },
  {
    id: 'nav.panRight',
    keys: ['arrowright'],
    modifiers: ['shift'],
    description: 'Pan canvas right',
    scope: 'canvas',
    category: 'navigation',
  },

  // ─── Tools ───────────────────────────────────────────────────────
  {
    id: 'tool.select',
    keys: ['v'],
    description: 'Select tool',
    scope: 'canvas',
    category: 'tools',
  },
  {
    id: 'tool.text',
    keys: ['t'],
    description: 'Text tool',
    scope: 'canvas',
    category: 'tools',
  },
  {
    id: 'tool.draw',
    keys: ['p'],
    description: 'Draw tool',
    scope: 'canvas',
    category: 'tools',
  },
  {
    id: 'tool.line',
    keys: ['l'],
    description: 'Line tool',
    scope: 'canvas',
    category: 'tools',
  },
  {
    id: 'tool.rectangle',
    keys: ['r'],
    description: 'Rectangle tool',
    scope: 'canvas',
    category: 'tools',
  },
  {
    id: 'tool.hand',
    keys: ['h'],
    description: 'Hand tool (pan)',
    scope: 'canvas',
    category: 'tools',
  },

  // ─── Layers ──────────────────────────────────────────────────────
  {
    id: 'layer.new',
    keys: ['l'],
    modifiers: ['ctrl', 'shift'],
    description: 'Create new layer',
    scope: 'global',
    category: 'layers',
  },
  {
    id: 'layer.duplicate',
    keys: ['j'],
    modifiers: ['ctrl'],
    description: 'Duplicate active layer',
    scope: 'global',
    category: 'layers',
  },
  {
    id: 'layer.delete',
    keys: ['backspace'],
    modifiers: ['ctrl', 'shift'],
    description: 'Delete active layer',
    scope: 'global',
    category: 'layers',
  },
  {
    id: 'layer.moveUp',
    keys: ['arrowup'],
    modifiers: ['ctrl', 'shift'],
    description: 'Move layer up',
    scope: 'global',
    category: 'layers',
  },
  {
    id: 'layer.moveDown',
    keys: ['arrowdown'],
    modifiers: ['ctrl', 'shift'],
    description: 'Move layer down',
    scope: 'global',
    category: 'layers',
  },
  {
    id: 'layer.toggleVisibility',
    keys: ['h'],
    modifiers: ['ctrl'],
    description: 'Toggle layer visibility',
    scope: 'global',
    category: 'layers',
  },
  {
    id: 'layer.toggleLock',
    keys: ['l'],
    modifiers: ['ctrl'],
    description: 'Toggle layer lock',
    scope: 'global',
    category: 'layers',
  },

  // ─── Components ──────────────────────────────────────────────────
  {
    id: 'component.library',
    keys: ['b'],
    modifiers: ['ctrl'],
    description: 'Open component library',
    scope: 'global',
    category: 'components',
  },
  {
    id: 'component.create',
    keys: ['k'],
    modifiers: ['ctrl'],
    description: 'Create new component',
    scope: 'global',
    category: 'components',
  },
  {
    id: 'component.edit',
    keys: ['enter'],
    description: 'Edit selected component',
    scope: 'canvas',
    category: 'components',
  },

  // ─── System ──────────────────────────────────────────────────────
  {
    id: 'system.save',
    keys: ['s'],
    modifiers: ['ctrl'],
    description: 'Save diagram',
    scope: 'global',
    category: 'system',
  },
  {
    id: 'system.saveAs',
    keys: ['s'],
    modifiers: ['ctrl', 'shift'],
    description: 'Save diagram as',
    scope: 'global',
    category: 'system',
  },
  {
    id: 'system.new',
    keys: ['n'],
    modifiers: ['ctrl'],
    description: 'New diagram',
    scope: 'global',
    category: 'system',
  },
  {
    id: 'system.open',
    keys: ['o'],
    modifiers: ['ctrl'],
    description: 'Open diagram',
    scope: 'global',
    category: 'system',
  },
  {
    id: 'system.help',
    keys: ['?'],
    modifiers: ['shift'],
    description: 'Show keyboard shortcuts',
    scope: 'global',
    category: 'system',
  },
  {
    id: 'system.settings',
    keys: [','],
    modifiers: ['ctrl'],
    description: 'Open settings',
    scope: 'global',
    category: 'system',
  },
  {
    id: 'system.search',
    keys: ['p'],
    modifiers: ['ctrl'],
    description: 'Command palette',
    scope: 'global',
    category: 'system',
  },
];
