/**
 * Tinker Design System - Theme Definitions
 * 
 * 14 designer-inspired themes, each with light and dark mode variants.
 * Default: Standard theme, Light mode
 */

export interface ColorTokens {
  background: string;
  foreground: string;
  muted: string;
  mutedForeground: string;
  border: string;
  accent: string;
  accentForeground: string;
  success: string;
  warning: string;
  error: string;
  info: string;
  terminal: string;
  terminalText: string;
}

export interface Theme {
  name: string;
  description: string;
  light: ColorTokens;
  dark: ColorTokens;
}

export type ThemeId =
  | 'standard'
  | 'dieter'
  | 'warhol'
  | 'moebius'
  | 'peanuts'
  | 'bass'
  | 'albers'
  | 'mondrian'
  | 'ghibli'
  | 'kare'
  | 'klein'
  | 'morris'
  | 'vignelli'
  | 'hockney';

export type Mode = 'light' | 'dark';

export const DEFAULT_THEME: ThemeId = 'standard';
export const DEFAULT_MODE: Mode = 'light';

export const themes: Record<ThemeId, Theme> = {
  standard: {
    name: 'Standard',
    description: 'Clean, modern, neutral',
    light: {
      background: '#ffffff',
      foreground: '#0a0a0a',
      muted: '#f4f4f5',
      mutedForeground: '#71717a',
      border: '#e4e4e7',
      accent: '#18181b',
      accentForeground: '#fafafa',
      success: '#22c55e',
      warning: '#f59e0b',
      error: '#ef4444',
      info: '#3b82f6',
      terminal: '#1e1e1e',
      terminalText: '#d4d4d4',
    },
    dark: {
      background: '#0a0a0a',
      foreground: '#fafafa',
      muted: '#18181b',
      mutedForeground: '#a1a1aa',
      border: '#27272a',
      accent: '#fafafa',
      accentForeground: '#0a0a0a',
      success: '#22c55e',
      warning: '#f59e0b',
      error: '#ef4444',
      info: '#3b82f6',
      terminal: '#0d0d0d',
      terminalText: '#d4d4d4',
    },
  },
  dieter: {
    name: 'Dieter Rams',
    description: 'Braun-inspired, warm & restrained',
    light: {
      background: '#f5f3ef',
      foreground: '#2d2926',
      muted: '#e8e4dc',
      mutedForeground: '#8c857a',
      border: '#d4cfc4',
      accent: '#d4a017',
      accentForeground: '#2d2926',
      success: '#5d6f45',
      warning: '#c68c3c',
      error: '#b44437',
      info: '#6b8fa3',
      terminal: '#2d2926',
      terminalText: '#d4cfc4',
    },
    dark: {
      background: '#1a1816',
      foreground: '#e8e4dc',
      muted: '#2d2926',
      mutedForeground: '#9c958b',
      border: '#3d3833',
      accent: '#d4a017',
      accentForeground: '#1a1816',
      success: '#7a9562',
      warning: '#d4a017',
      error: '#c45c4f',
      info: '#7fa3b8',
      terminal: '#141210',
      terminalText: '#d4cfc4',
    },
  },
  warhol: {
    name: 'Andy Warhol',
    description: 'Pop Art, bold & electric',
    light: {
      background: '#fefefe',
      foreground: '#0d0d0d',
      muted: '#f5f5f5',
      mutedForeground: '#666666',
      border: '#e0e0e0',
      accent: '#ff6ec7',
      accentForeground: '#0d0d0d',
      success: '#32cd32',
      warning: '#ffe135',
      error: '#ff5f1f',
      info: '#00d4ff',
      terminal: '#0d0d0d',
      terminalText: '#ff6ec7',
    },
    dark: {
      background: '#0d0d0d',
      foreground: '#fefefe',
      muted: '#1a1a1a',
      mutedForeground: '#999999',
      border: '#333333',
      accent: '#ff6ec7',
      accentForeground: '#0d0d0d',
      success: '#32cd32',
      warning: '#ffe135',
      error: '#ff5f1f',
      info: '#00d4ff',
      terminal: '#000000',
      terminalText: '#00d4ff',
    },
  },
  moebius: {
    name: 'Mœbius',
    description: 'Ethereal sci-fi landscapes',
    light: {
      background: '#fdf6e3',
      foreground: '#3d3a35',
      muted: '#f5ebe0',
      mutedForeground: '#8b8177',
      border: '#e8dfd4',
      accent: '#7b68ee',
      accentForeground: '#fdf6e3',
      success: '#6b9080',
      warning: '#e07850',
      error: '#c06060',
      info: '#5d8aa8',
      terminal: '#2d2a26',
      terminalText: '#e8c39e',
    },
    dark: {
      background: '#1a1d21',
      foreground: '#e8dfd4',
      muted: '#252a30',
      mutedForeground: '#a8a090',
      border: '#3a3f48',
      accent: '#9d8df1',
      accentForeground: '#1a1d21',
      success: '#7faa96',
      warning: '#e89070',
      error: '#d08080',
      info: '#7ba8c8',
      terminal: '#12151a',
      terminalText: '#e8c39e',
    },
  },
  peanuts: {
    name: 'Peanuts',
    description: 'Friendly, nostalgic & warm',
    light: {
      background: '#fffef9',
      foreground: '#2d2d2d',
      muted: '#fff8e7',
      mutedForeground: '#6b6b6b',
      border: '#e8e0d0',
      accent: '#ffd93d',
      accentForeground: '#2d2d2d',
      success: '#7cb342',
      warning: '#ffb74d',
      error: '#c41e3a',
      info: '#87ceeb',
      terminal: '#2d2d2d',
      terminalText: '#fff8e7',
    },
    dark: {
      background: '#1e1e1c',
      foreground: '#f5f5f0',
      muted: '#2a2a28',
      mutedForeground: '#a0a090',
      border: '#3d3d38',
      accent: '#ffd93d',
      accentForeground: '#1e1e1c',
      success: '#8bc34a',
      warning: '#ffc857',
      error: '#e74c3c',
      info: '#87ceeb',
      terminal: '#151514',
      terminalText: '#ffd93d',
    },
  },
  bass: {
    name: 'Saul Bass',
    description: 'Cinematic, dramatic tension',
    light: {
      background: '#f5f0e6',
      foreground: '#0d0d0d',
      muted: '#ebe5d9',
      mutedForeground: '#5c5c5c',
      border: '#d4cfc4',
      accent: '#e85d04',
      accentForeground: '#f5f0e6',
      success: '#2d6a4f',
      warning: '#ffb703',
      error: '#9b2335',
      info: '#457b9d',
      terminal: '#0d0d0d',
      terminalText: '#e85d04',
    },
    dark: {
      background: '#0d0d0d',
      foreground: '#f5f0e6',
      muted: '#1a1a1a',
      mutedForeground: '#a0a0a0',
      border: '#2d2d2d',
      accent: '#e85d04',
      accentForeground: '#0d0d0d',
      success: '#40916c',
      warning: '#ffb703',
      error: '#c1121f',
      info: '#5d9dc5',
      terminal: '#050505',
      terminalText: '#e85d04',
    },
  },
  albers: {
    name: 'Josef Albers',
    description: 'Bauhaus color theory',
    light: {
      background: '#faf8f5',
      foreground: '#2c3e50',
      muted: '#f0ebe3',
      mutedForeground: '#6c757d',
      border: '#e0d8cc',
      accent: '#e36414',
      accentForeground: '#faf8f5',
      success: '#264653',
      warning: '#f4a261',
      error: '#9b2226',
      info: '#2a9d8f',
      terminal: '#264653',
      terminalText: '#f4a261',
    },
    dark: {
      background: '#1a1f24',
      foreground: '#f0ebe3',
      muted: '#252d35',
      mutedForeground: '#98a4ae',
      border: '#364049',
      accent: '#e36414',
      accentForeground: '#1a1f24',
      success: '#40798c',
      warning: '#f4a261',
      error: '#c44536',
      info: '#48bfa9',
      terminal: '#141a1f',
      terminalText: '#f4a261',
    },
  },
  mondrian: {
    name: 'Mondrian',
    description: 'De Stijl, primary colors',
    light: {
      background: '#fefefe',
      foreground: '#000000',
      muted: '#f5f5f5',
      mutedForeground: '#4a4a4a',
      border: '#000000',
      accent: '#dd0100',
      accentForeground: '#fefefe',
      success: '#0000ff',
      warning: '#fac901',
      error: '#dd0100',
      info: '#0000ff',
      terminal: '#000000',
      terminalText: '#fefefe',
    },
    dark: {
      background: '#0a0a0a',
      foreground: '#fefefe',
      muted: '#1a1a1a',
      mutedForeground: '#b0b0b0',
      border: '#fefefe',
      accent: '#dd0100',
      accentForeground: '#fefefe',
      success: '#4169e1',
      warning: '#fac901',
      error: '#dd0100',
      info: '#4169e1',
      terminal: '#000000',
      terminalText: '#fac901',
    },
  },
  ghibli: {
    name: 'Studio Ghibli',
    description: 'Magical naturalism',
    light: {
      background: '#f8f6f0',
      foreground: '#36454f',
      muted: '#f0ede5',
      mutedForeground: '#6b7b7f',
      border: '#ddd8cc',
      accent: '#4a7c59',
      accentForeground: '#f8f6f0',
      success: '#4a7c59',
      warning: '#ff7f50',
      error: '#c75050',
      info: '#89cff0',
      terminal: '#36454f',
      terminalText: '#f0ede5',
    },
    dark: {
      background: '#1c2126',
      foreground: '#f0ede5',
      muted: '#262d33',
      mutedForeground: '#98a8ac',
      border: '#3a4248',
      accent: '#5d9b6d',
      accentForeground: '#1c2126',
      success: '#5d9b6d',
      warning: '#ff9068',
      error: '#e07070',
      info: '#89cff0',
      terminal: '#141a1e',
      terminalText: '#89cff0',
    },
  },
  kare: {
    name: 'Susan Kare',
    description: 'Classic Mac, friendly computing',
    light: {
      background: '#c4b49a',
      foreground: '#000000',
      muted: '#b8a88e',
      mutedForeground: '#3d3d3d',
      border: '#9a8a70',
      accent: '#000000',
      accentForeground: '#c4b49a',
      success: '#33ff33',
      warning: '#ffcc00',
      error: '#ff0000',
      info: '#0066cc',
      terminal: '#000000',
      terminalText: '#33ff33',
    },
    dark: {
      background: '#1a1a1a',
      foreground: '#c4b49a',
      muted: '#2a2a2a',
      mutedForeground: '#8a7a60',
      border: '#4a4a4a',
      accent: '#33ff33',
      accentForeground: '#000000',
      success: '#33ff33',
      warning: '#ffcc00',
      error: '#ff3333',
      info: '#4488dd',
      terminal: '#000000',
      terminalText: '#33ff33',
    },
  },
  klein: {
    name: 'Yves Klein',
    description: 'IKB, monochrome intensity',
    light: {
      background: '#ffffff',
      foreground: '#0a0a0a',
      muted: '#f0f4f8',
      mutedForeground: '#5a6a7a',
      border: '#d0daea',
      accent: '#002fa7',
      accentForeground: '#ffffff',
      success: '#002fa7',
      warning: '#d4af37',
      error: '#c41e3a',
      info: '#002fa7',
      terminal: '#002fa7',
      terminalText: '#ffffff',
    },
    dark: {
      background: '#0a0a0a',
      foreground: '#ffffff',
      muted: '#141824',
      mutedForeground: '#8090a0',
      border: '#202838',
      accent: '#002fa7',
      accentForeground: '#ffffff',
      success: '#3050c0',
      warning: '#d4af37',
      error: '#e05050',
      info: '#3050c0',
      terminal: '#001040',
      terminalText: '#ffffff',
    },
  },
  morris: {
    name: 'William Morris',
    description: 'Arts & Crafts, artisanal',
    light: {
      background: '#f5f2e8',
      foreground: '#2d2416',
      muted: '#ebe5d5',
      mutedForeground: '#6b5d4d',
      border: '#d4c8b0',
      accent: '#4e6e4e',
      accentForeground: '#f5f2e8',
      success: '#4e6e4e',
      warning: '#cc7722',
      error: '#a52a2a',
      info: '#4b0082',
      terminal: '#2d2416',
      terminalText: '#ebe5d5',
    },
    dark: {
      background: '#1a1612',
      foreground: '#ebe5d5',
      muted: '#2a241c',
      mutedForeground: '#a09080',
      border: '#3d352a',
      accent: '#6a9a6a',
      accentForeground: '#1a1612',
      success: '#6a9a6a',
      warning: '#e09040',
      error: '#c05050',
      info: '#7050a0',
      terminal: '#100e0a',
      terminalText: '#cc7722',
    },
  },
  vignelli: {
    name: 'Massimo Vignelli',
    description: 'Modernist systems design',
    light: {
      background: '#ffffff',
      foreground: '#1c1c1c',
      muted: '#f5f5f5',
      mutedForeground: '#6d6d6d',
      border: '#d0d0d0',
      accent: '#ee2a24',
      accentForeground: '#ffffff',
      success: '#00a651',
      warning: '#fccc0a',
      error: '#ee2a24',
      info: '#0039a6',
      terminal: '#1c1c1c',
      terminalText: '#ffffff',
    },
    dark: {
      background: '#1c1c1c',
      foreground: '#ffffff',
      muted: '#2a2a2a',
      mutedForeground: '#9d9d9d',
      border: '#404040',
      accent: '#ee2a24',
      accentForeground: '#ffffff',
      success: '#00c461',
      warning: '#fccc0a',
      error: '#ee2a24',
      info: '#2060c6',
      terminal: '#0a0a0a',
      terminalText: '#ee2a24',
    },
  },
  hockney: {
    name: 'David Hockney',
    description: 'California pools & sunshine',
    light: {
      background: '#fefcf8',
      foreground: '#2a3a4a',
      muted: '#f5f8fc',
      mutedForeground: '#6080a0',
      border: '#d0e0f0',
      accent: '#00b4d8',
      accentForeground: '#fefcf8',
      success: '#90be6d',
      warning: '#ffd166',
      error: '#ef476f',
      info: '#00b4d8',
      terminal: '#2a3a4a',
      terminalText: '#00b4d8',
    },
    dark: {
      background: '#1a2430',
      foreground: '#f5f8fc',
      muted: '#243040',
      mutedForeground: '#90a8c0',
      border: '#304050',
      accent: '#00b4d8',
      accentForeground: '#1a2430',
      success: '#a0d080',
      warning: '#ffe080',
      error: '#ff6090',
      info: '#20c8f0',
      terminal: '#101820',
      terminalText: '#00b4d8',
    },
  },
};

export const themeIds = Object.keys(themes) as ThemeId[];
